/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ReactNode } from "react";
import Nav from "@/components/Nav";
import { SessionProvider } from "next-auth/react";
import { GlobalProvider } from "@/app/context/GlobalContext";
 // Adjust the path as needed
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
};
const Layout = ({ children }: LayoutProps) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <main >

          <div >
           <GlobalProvider>
            <SessionProvider>
            <Nav />
              {children}
            </SessionProvider>
           </GlobalProvider>
          </div>
        </main>
      </body>
    </html>
  );
};

export { metadata };
export default Layout;
